apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.shortname" . }}-api-configmap
  labels:
  {{- include "api.labels" . | nindent 4 }}
data:
  {{- if .Values.api.environment }}
  {{- range $key, $val := .Values.api.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  SERVER_PORT: "{{ .Values.api.containerPorts.http }}"
  CORS_ALLOWED_ORIGINS: "http://hateoas-fullstack-ui.github.io"