apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.shortname" . }}-ui
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent 6 }}
  {{- if .Values.global.updateStrategy }}
  replicas: {{ .Values.ui.replicaCount }}
  strategy: {{- toYaml .Values.global.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.global.imagePullSecrets | nindent 4 }}
      {{- end }}
      containers:
        {{- if .Values.ui.extraSideContainers }}
        {{ tpl .Values.ui.extraSideContainers . | indent 8 }}
        {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          {{- if .Values.ui.command }}
          command:
          {{ tpl .Values.ui.command . | indent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.containerPorts.http }}
          {{- if .Values.ui.livenessProbe.enabled }}
          livenessProbe: {{- omit .Values.ui.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- else if .Values.ui.customLivenessProbe }}
          livenessProbe: {{- toYaml .Values.ui.customLivenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.ui.readinessProbe.enabled }}
          readinessProbe: {{- omit .Values.ui.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- else if .Values.ui.customReadinessProbe }}
          readinessProbe: {{- toYaml .Values.ui.customReadinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.ui.resources }}
          resources: {{- toYaml .Values.ui.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.ui.extraVolumeMounts }}
          {{- toYaml .Values.ui.extraVolumeMounts | nindent 12 }}
      {{- end }}
      {{- if .Values.ui.extraInitContainers }}
      initContainers:
      {{ tpl .Values.ui.extraInitContainers . | indent 8 }}
      {{- end }}
      {{- if .Values.ui.extraVolumes }}
      volumes:
      {{- if .Values.ui.extraVolumes }}
      {{- toYaml .Values.ui.extraVolumes | nindent 8 }}
  {{- end }}
  {{- end }}