export const GET_CAPABILITIES = 'GET_CAPABILITIES';
export const DELETE_CAPABILITY = 'DELETE_CAPABILITY';
export const ADD_CAPABILITY = 'ADD_CAPABILITY';
export const GET_ERRORS = 'GET_ERRORS';
export const GET_CAPABILITY = 'GET_CAPABILITY';
export const CLEAR_CAPABILITY_CLOSE_MODAL = 'CLEAR_CAPABILITY_CLOSE_MODAL';
export const UPDATE_CAPABILITY = 'UPDATE_CAPABILITY';